apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: jy2545acr.azurecr.io/backend-java
    newTag: main-20240820135816

commonLabels:
  app: backend-java
  environment: dev
